name: f_authenticator
description: 2FA Authentication package for flutter.
version: 0.0.3
homepage:
issue_tracker: https://github.com/Odinachi/f_autheticator/issues
repository: https://github.com/Odinachi/f_autheticator

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  otp: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
